### ISSUE TITLE
RK 95 Ghost mg assistant.

### ISSUE THREAD

**Issue by anssirantanen** [FinModA3/development#15] opened 2016-09-23 19:26 UTC
in editor there is extra mg assistant which doesn't have any weapons. Also no PKM cases.
from editor preview should have fin_Sniper_TRG42 as weapon.

**Comment by Arskah** [comment] 2016-09-24 14:53
Caused by bad release init and fixed in new release branch. There should be no extra assistant anymore. Needs to be verified.

**Closed as completed** 2016-09-26 14:19 UTC
Labels: bug, resolved
