### ISSUE TITLE
AI not working with APILAS, KES, OR IT OHJ

### ISSUE THREAD

**Issue by Hege123** [FinModA3/development#39] opened 2016-11-21 11:20 UTC
AI does not fire these weapons at any target at any situation. Tried engage at will, target and fire commands. Issue is global.

**Comment by saunatyyny** [comment] 2016-11-21 15:50
Won't fix. AI can't handle our reloading mechanism and therefor tries to fire unprepared launcher. Issue will be closed. Try using vanilla rpg launcher.

**Comment by Arskah** [comment] 2016-11-22 20:47
Can't be reload mechanism, since ITOHJ isn't using the script.

aiAmmoUsageFlags should be checked in cfgAmmo. Also need to be checked that the reload script for launchers give AI rocket also

**Comment by Hege123** [comment] 2016-11-22 21:01
Actually just noticed that IT ohj works, but how come that RHS rpg's work,
but KES does not? Same kind of mechanisms in use, but are they implementes
differently? I mean, it is kinda major issue if AI can not use any FDF
launchers. One would like to create scenarios where AI can destroy enemy
vehicles and armor with proper launchers! =D Hoping you find some kind of
solution for this at some point. Loving the work you've been doing this far!

Make it great!

22.11.2016 10.47 ip. "Arskah" notifications@github.com kirjoitti:

Can't be reload mechanism, since ITOHJ isn't using the script.

aiAmmoUsageFlags should be checked in cfgAmmo

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/FinModA3/development/issues/39#issuecomment-262360936,
or mute the thread

**Comment by Hege123** [comment] 2016-11-22 21:01
Actually just noticed that IT ohj works, but how come that RHS rpg's work,
but KES does not? Same kind of mechanisms in use, but are they implementes
differently? I mean, it is kinda major issue if AI can not use any FDF
launchers. One would like to create scenarios where AI can destroy enemy
vehicles and armor with proper launchers! =D Hoping you find some kind of
solution for this at some point. Loving the work you've been doing this far!

Make it great!

22.11.2016 10.47 ip. "Arskah" notifications@github.com kirjoitti:

**Comment by Hege123** [comment] 2016-11-22 21:06
And to confirm, for example AAF unit can fire KES 88 and other FDF AT
weapons. There truly is something wrong with FDF units.

22.11.2016 11.01 ip. "Heikki Rissanen" heikki.levels@gmail.com kirjoitti:

**Comment by Arskah** [comment] 2016-11-22 21:26
There is difference in the scripts used. You can find our script from
https://github.com/FinModA3/development/tree/master/%40Finmod/addons/fin_launchers_c/functions
Most significant difference is that our launchers need the reload to be triggered with R, that is, there will be an reload animation which sets up the launcher for firing

**Comment by Hege123** [comment] 2016-11-22 21:29
Full listing: AAF can fire: 66 KES 88 and APILAS. KES 12 Wont work, either
of them. Therefor FDF cant fire any of these weapons. Just seems kinda odd.

22.11.2016 11.26 ip. "Arskah" notifications@github.com kirjoitti:

**Comment by Arskah** [comment] 2016-11-27 15:19
Own testing:
Seems to be that the problem is that AI is missing the magazine, therefore it doesn't think it should change to launcher, which would actually give it the mag it needs.

Going to rework the script so that AI will have one mag, but never has it loaded when launcher is on back.

Tested with vanilla NATO unit, with and without mag. I'm pretty sure that Hege's different results with AI units were because of some of the test units had mag and some not.

**Comment by Arskah** [comment] 2017-05-25 14:43
Fixed

**Closed as completed by Arskah** 2017-05-25 14:43 UTC
Labels: bug, resolved, Need more information
